Colourise Configutation

clrs:6
kol:\c
shit:# of colours
c1:#091E4B
c2:#E69F30
c3:#8C43DC
c4:#DE2369
c5:#30CEF9
c6:#000000
c7:#F62CC0
word:true
bounce:false
cont:false
across:true
k1:true
k3:false
k4:false
k2:false
mktag:false
randoom:false
match13:false
match31:false
match14:false
match34:false
match131:false
invert:false
grad:false
hueshort:true
grtype:HSL
gradn:false
double:false
ast:false
tuneall:false
tfmode:all tags
reverse:false
rem:false
rept:false
help:: Help Menu :
