Masquerade config

mask:from clip
masknew:false
save:false
remask:false
maskname:mask name here
an8:an8
mblur:1
keepblur:false
mbdist:6
mbalfa:80
mb3:false
shiftby:1
ash:α
s_alfa:StrikeAlpha
sa_max:20
gam:false
deltas1:
deltas0:
deltau1:
deltau0:
deltabell:
deltawave:
